builders:
  - python
upstream:
  - eduid-userdb
triggers:
  cron: "@weekly"
slack:
  room: "eduid-builds"
python_module: eduid_am
python_source_directory: ./src/
clean_workspace: true
publish_over_ssh:
  - pypi.sunet.se
pre_build_script:
  - echo "apt-get -y install xmlsec1"
post_build_script:
  - echo "post build"
build_in_docker:
  image: docker.sunet.se/sunet/docker-jenkins-job
  
extra_jobs:
  - name: eduid-am-docker
    builders:
      - docker
    environment_variables:
      TESTVAR: "mipp-mupp"
    docker_name: eduid/eduid-am
    docker_tags:
      - "${TESTVAR}"
    managed_scripts:
      - docker_build_prep.sh
      - docker_tag.sh
    triggers:
      github_push: false
      cron: ~
    upstream:
      - eduid-am
    
    
    
