#docker_disable
builders:
  - test
upstream:
  - upstream1
  - upstream2
downstream:
  - downstream1
triggers:
  cron: @yearly
slack:
  room: "slack_room"
  custom_message: "this is a custom message"
  sendas: "a sender"
jabber: "channel"
